### ISSUE TITLE
 Question: How to style the expander arrow color in CSS

### ISSUE THREAD

**Issue by Crystal4276** [nwg-piotr/nwg-menu#28]
I'm trying to customize the appearance of nwg-menu using CSS, specifically to change the color of the expander arrows that appear next to expandable menu items.

![2025-01-10-125237](https://github.com/user-attachments/assets/d83ccae0-923c-4dee-a4fe-f6bf59b28685)

Current CSS for menu items for hover style:
```css
list row:hover {
    background-color: @green;
    border-radius: 1rem;
    border: 1px solid @overlay0;
    transition: none;
    color: @mantle;
}
```
I've tried various CSS selectors to target the arrow, including:

list row:hover expander
list row:hover arrow
list row:hover box arrow
list row:hover > arrow
list row:hover -gtk-expander-arrow

None of these selectors seem to affect the arrow color. Could you please provide guidance on:

What CSS selector should be used to style these expander arrows?
Are there any specific properties or limitations regarding arrow styling?

Thank you for your help!

**Comment by Crystal4276** [comment]
Ok, at least the arrow is not hard-coded and its styling can be changed ?

**Comment by nwg-piotr** [comment]
Actually it's the `pan-end-symbolic` icon. See: https://github.com/nwg-piotr/nwg-menu/blob/2a291418aa56b4f8c124b370d08e015554bcf5ef/uicomponents.go#L114

**Comment by Crystal4276** [comment]
I found a CSS selector that work:
```css
image:nth-child(3) {
    background-color: @green;
    color: @red;
}
```

![2025-01-10-201810](https://github.com/user-attachments/assets/a12277de-7be5-4294-a022-521383e7d073)

Now, i'm struggling to find a way to recolor the icon. Only the background color is working.

**Comment by Crystal4276** [comment]
At the end i was not able to recolor the arrow icons.
I took the option to just hide them

But in the process i could learn a lot about CSS as I had 0 prior knowledge.
So I'm putting below what i have documented of the CSS selector for someone passing by.
This could save some headache for others.
<details>
<summary>Main CSS selector for nwg-menu </summary>

```css
@import "mocha.css";

window {
    background-color: transparent;
    font-family: Symbols Nerd Font Mono;
    font-size: 20px;
}

/* Main box of the menu */
window > box {
    background-color: @mantle;
    border-radius: 1rem;
    border: 1px solid @overlay0;
    margin: 1px; 
}

/* Search field box */
entry {
    background-color: @mantle;
    box-shadow: none; /* Remove the border accent color defined by the GTK theme */
    padding: 0.2rem 0rem;
    border-radius: 0.5rem;
    border-bottom: 1px solid @overlay2;
    font-size: 24px;
}

/* Folders box */
window:dir(ltr).background > box:dir(ltr).vertical > box:dir(ltr).horizontal > box:dir(ltr).horizontal > box:dir(ltr).vertical > list:dir(ltr):nth-child(1) {
    margin-top: 65px;
    margin-right: 6px;
    border-radius: 1rem;
    border: 1px solid @overlay0;
}

/* Favorites box */
window.background:dir(ltr) > box.vertical:dir(ltr) > box.horizontal:dir(ltr):nth-child(1) > box.horizontal:dir(ltr):nth-child(1) > box.vertical:dir(ltr):nth-child(1) > list:dir(ltr):nth-child(3) {
    border-radius: 1rem;
    border: 1px solid @overlay0;
    background: @base;
}

/* Main categories box */
window.background:dir(ltr) > box.vertical:dir(ltr) > box.horizontal:dir(ltr):nth-child(1) > box.horizontal:dir(ltr):nth-child(1) > box.vertical:dir(ltr):nth-child(1) > list:dir(ltr):nth-child(2) {
    background: @base;
    border-radius: 1.0rem;
    border: 1px solid @overlay0;
}

/* Window scroll box */
scrolledwindow {
    background: @base;
    border-radius: 1.0rem;
    border: 1px solid @overlay0;
    margin: -7px 6px 0px 0px;
    padding: 5px 5px 5px 5px;
}

scrolledwindow list row {
    margin-right: 30px;
}

scrollbar {
    min-width: 25px;
    background: transparent;
    border: 1px solid transparent;
}

scrollbar slider {
    background-color: @overlay0;
}

scrollbar slider:hover {
    background-color: @overlay1; 
}

/* General styling for items in list */
list row {
    padding: 5px;
    margin: 2px;
    border-radius: 1rem;
    border: 1px solid transparent;
    transition: none;
    color: @text;
}

list row:hover {
    background-color: @green;
    border-radius: 1rem;
    border: 1px solid transparent;
    transition: none;
    color: @mantle;
}

list row:selected {
    background-color: @green;
    border-radius: 1rem;
    border: 1px solid @overlay0;
    transition: none;
}

list row:selected label {
    color: @mantle;
}

/* Remove the arrow pointing to the right in each item of the main categories list */
list row:hover image:nth-child(3) {
    background-color: transparent;
    opacity: 0;
}

list row image:nth-child(3) {
    background-color: transparent;
    opacity: 0;
}

/* Styling of Lock/Logout/reboot/power-off buttons */
button {
    background: none;
    border-radius: 1rem;
    border: 1px solid transparent;
}

button:hover {
    background-color: rgba (255, 255, 255, 0.1);
    border-radius: 1rem;
    border: 1px solid @overlay0;
}

</details>
```
And a screenshot of the CSS styling just above.
![2025-01-11-164718](https://github.com/user-attachments/assets/687cfa1e-788a-4a9b-88b6-386f49337ef1)
